### ISSUE TITLE
Missing credentials.py

### ISSUE THREAD

**Issue by Rushi98** [OSDLabs/Ingress#4]
Getting this error while running `python3 manage.py createsuperuser`

```txt
 File "/home/rushi/ingress/ingress/src/ingress/settings.py", line 3, in <module>
    from .credentials import *
ImportError: No module named 'ingress.credentials'
```

 **Observation**: `.gitignore` has `credentials.py` in it. Why?

**Comment by erag996** [comment]
@Rushi98  try adding an empty file name credentials.py
$ touch credentials.py

**Comment by Rushi98** [comment]
`touch ingress/credentials.py` worked.
